name: Build and Push FastAPI Docker Image

on:
  push:
    paths:
      - 'app.py'
      - 'src/**'
      - 'requirements.txt'
      - '.github/workflows/fastapi-docker-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.fastapi
          push: true
          tags: praj-1717/advance-question-generator-fastapi:latest
