name: Build and Push FastAPI Docker Image

on:
  push:
    branches:
      - main # Specify the branch to trigger on. Adjust as needed.
    paths:
      - 'app.py'
      - 'src/**'
      - 'requirements.txt'
      - '.github/workflows/fastapi-docker-image.yml'
      - 'Dockerfile.fastapi' # Ensure Dockerfile changes also trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Ensure the correct build context
          file: Dockerfile.fastapi # Point to the correct Dockerfile
          push: true # Push the built image to Docker Hub
          tags: |
            prajwal1717/advance-question-generator-fastapi:latest

      - name: Post-build cleanup
        run: docker system prune -f # Optional cleanup step to remove unused data
